export const API = "http://localhost:8080/";

export const GET_WORKOUTS_REQUEST = "GET_WORKOUTS_REQUEST";
export const GET_WORKOUTS_SUCCESS = "GET_WORKOUTS_SUCCESS";
export const GET_WORKOUTS_FAILURE = "GET_WORKOUTS_FAILURE";
